'use server';

import { createClient } from '@/lib/supabase/server';
import { revalidatePath } from 'next/cache';

export async function createProject(formData: FormData) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) {
    return { error: 'No autorizado' };
  }

  const name = formData.get('name') as string;
  const description = formData.get('description') as string;
  const clientId = formData.get('clientId') as string;

  const { data, error } = await supabase
    .from('projects')
    .insert([
      {
        architect_id: user.id,
        client_id: clientId || null,
        name,
        description,
        status: 'active',
        // portal_token will be generated by the database default
      },
    ])
    .select()
    .single();

  if (error) {
    return { error: error.message };
  }

  revalidatePath('/dashboard');
  return { success: true, project: data };
}

export async function getProjects() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return [];

  const { data, error } = await supabase
    .from('projects')
    .select(`
      *,
      clients (
        name
      )
    `)
    .eq('architect_id', user.id)
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching projects:', error);
    return [];
  }

  return data;
}

export async function getClients() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();

  if (!user) return [];

  const { data, error } = await supabase
    .from('clients')
    .select('*')
    .eq('architect_id', user.id)
    .order('name', { ascending: true });

  if (error) {
    console.error('Error fetching clients:', error);
    return [];
  }

  return data;
}
